# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Dog.create!([
  {
    breed: "Labrador Retriever",
    breed_group: "Sporting Group",
    breed_summary: "Labrador Retrievers were bred as a retrieving gun dog.",
    image_file_name: "breed-labrador-retriever.jpg",
    height_min: 21.5,
    height_max: 24.5,
    weight_min: 55,
    weight_max: 80,
    life_min: 10,
    life_max: 12,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 5,
    trainability: 5,
    energy_level: 5,
    shedding: true,
    popularity_rank: 1
  },
    {
    breed: "German Shepherd Dog",
    breed_group: "Herding Group",
    breed_summary: "Intelligent and brave",
    image_file_name: "breed-german-shepherd.jpg",
    height_min: 22,
    height_max: 26,
    weight_min: 50,
    weight_max: 90,
    life_min: 7,
    life_max: 10,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 4,
    trainability: 5,
    energy_level: 5,
    shedding: true,
    popularity_rank: 2
  },
  {
    breed: "Golden Retriever",
    breed_group: "Sporting Group",
    breed_summary: "Intelligent, friendly, and loyal.",
    image_file_name: "breed-golden-retriever.jpg",
    height_min: 21.5,
    height_max: 24,
    weight_min: 55,
    weight_max: 75,
    life_min: 10,
    life_max: 12,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 5,
    trainability: 5,
    energy_level: 5,
    shedding: true,
    popularity_rank: 3
  },
  {
    breed: "Bulldog",
    breed_group: "Non-Sporting Group",
    breed_summary: "Calm, brave, and friendly.",
    image_file_name: "breed-bulldog.jpg",
    height_min: 14,
    height_max: 15,
    weight_min: 40,
    weight_max: 50,
    life_min: 8,
    life_max: 10,
    affectionate: 5,
    kid_friendly: 4,
    stranger_friendly: 5,
    trainability: 3,
    energy_level: 2,
    shedding: true,
    popularity_rank: 4
  },
  {
    breed: "Beagle",
    breed_group: "Hound Group",
    breed_summary: "Happy, friendly, and inquisitive",
    image_file_name: "breed-beagle.jpg",
    height_min: 13,
    height_max: 15,
    weight_min: 20,
    weight_max: 30,
    life_min: 10,
    life_max: 15,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 5,
    trainability: 1,
    energy_level: 4,
    shedding: true,
    popularity_rank: 5
  },
  {
    breed: "French Bulldog",
    breed_group: "Non-Sporting Group",
    breed_summary: "Playful, intelligent, and adaptable.",
    image_file_name: "breed-french-bulldog.jpg",
    height_min: 11,
    height_max: 13,
    weight_min: 20,
    weight_max: 28,
    life_min: 10,
    life_max: 12,
    affectionate: 5,
    kid_friendly: 4,
    stranger_friendly: 4,
    trainability: 4,
    energy_level: 3,
    shedding: true,
    popularity_rank: 6
  },
  {
    breed: "Poodle",
    breed_group: "Non-Sporting Group",
    breed_summary: "Intelligent and active.",
    image_file_name: "breed-poodle.jpg",
    height_min: 10,
    height_max: 15,
    weight_min: 4,
    weight_max: 50,
    life_min: 10,
    life_max: 18,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 4,
    trainability: 5,
    energy_level: 4,
    shedding: false,
    popularity_rank: 7
  },
  {
    breed: "Rottweiler",
    breed_group: "Working Group",
    breed_summary: "Loyal and reserved.",
    image_file_name: "breed-rottweiler.jpg",
    height_min: 22,
    height_max: 27,
    weight_min: 77,
    weight_max: 130,
    life_min: 8,
    life_max: 10,
    affectionate: 5,
    kid_friendly: 4,
    stranger_friendly: 4,
    trainability: 4,
    energy_level: 4,
    shedding: true,
    popularity_rank: 8
  },
  {
    breed: "Yorkshire Terrier",
    breed_group: "Toy Group",
    breed_summary: "Feisty and fun.",
    image_file_name: "breed-yorkshire-terrier.jpg",
    height_min: 7,
    height_max: 8,
    weight_min: 7,
    weight_max: 7,
    life_min: 11,
    life_max: 15,
    affectionate: 4,
    kid_friendly: 2,
    stranger_friendly: 2,
    trainability: 3,
    energy_level: 5,
    shedding: false,
    popularity_rank: 9
  },
  {
    breed: "Boxer",
    breed_group: "Working Group",
    breed_summary: "Active, fun, and loyal.",
    image_file_name: "breed-boxer.jpg",
    height_min: 21.5,
    height_max: 25,
    weight_min: 50,
    weight_max: 80,
    life_min: 10,
    life_max: 12,
    affectionate: 5,
    kid_friendly: 4,
    stranger_friendly: 4,
    trainability: 4,
    energy_level: 5,
    shedding: true,
    popularity_rank: 10
  },

])