# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Dog.create!([
  {
    breed: "Labrador Retriever",
    breed_group: "Sporting Group",
    breed_summary: "Labrador Retrievers were bred as a retrieving gun dog.",
    image_file_name: "breed-labrador-retriever.jpg",
    height_min: 21.5,
    height_max: 24.5,
    weight_min: 55,
    weight_max: 80,
    dog_size: "Large",
    life_min: 10,
    life_max: 12,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 5,
    trainability: 5,
    energy_level: 5,
    shedding: true,
    popularity_rank: 1,
    history:
        "Labrador Retrievers are descended from retreiving dogs developed in Newfoundland. European settlers in Newfoundland had brought with them a dog called the St. Huberts Hound. It was used by the settlers to hunt and retrieve game and the retrieve fish.
        These retrieving dogs, at the time known at the St. John's dog, were brought back to England by fishing boat captains who could make money selling the dog."  },
    {
    breed: "German Shepherd Dog",
    breed_group: "Herding Group",
    breed_summary: "Intelligent and brave.",
    image_file_name: "breed-german-shepherd.jpg",
    height_min: 22,
    height_max: 26,
    weight_min: 50,
    weight_max: 90,
    dog_size: "Large",
    life_min: 7,
    life_max: 10,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 4,
    trainability: 5,
    energy_level: 5,
    shedding: true,
    popularity_rank: 2,
    history: ""
  },
  {
    breed: "Golden Retriever",
    breed_group: "Sporting Group",
    breed_summary: "Intelligent, friendly, and loyal.",
    image_file_name: "breed-golden-retriever.jpg",
    height_min: 21.5,
    height_max: 24,
    weight_min: 55,
    weight_max: 75,
    dog_size: "Large",
    life_min: 10,
    life_max: 12,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 5,
    trainability: 5,
    energy_level: 5,
    shedding: true,
    popularity_rank: 3,
    history: ""
  },
  {
    breed: "Bulldog",
    breed_group: "Non-Sporting Group",
    breed_summary: "Calm, brave, and friendly.",
    image_file_name: "breed-bulldog.jpg",
    height_min: 14,
    height_max: 15,
    weight_min: 40,
    weight_max: 50,
    dog_size: "Medium",
    life_min: 8,
    life_max: 10,
    affectionate: 5,
    kid_friendly: 4,
    stranger_friendly: 5,
    trainability: 3,
    energy_level: 1,
    shedding: true,
    popularity_rank: 4,
    history: ""
  },
  {
    breed: "Beagle",
    breed_group: "Hound Group",
    breed_summary: "Happy, friendly, and inquisitive.",
    image_file_name: "breed-beagle.jpg",
    height_min: 13,
    height_max: 15,
    weight_min: 20,
    weight_max: 30,
    dog_size: "Small and Medium",
    life_min: 10,
    life_max: 15,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 5,
    trainability: 1,
    energy_level: 4,
    shedding: true,
    popularity_rank: 5,
    history: ""
  },
  {
    breed: "French Bulldog",
    breed_group: "Non-Sporting Group",
    breed_summary: "Playful, intelligent, and adaptable.",
    image_file_name: "breed-french-bulldog.jpg",
    height_min: 11,
    height_max: 13,
    weight_min: 20,
    weight_max: 28,
    dog_size: "Small",
    life_min: 10,
    life_max: 12,
    affectionate: 5,
    kid_friendly: 4,
    stranger_friendly: 4,
    trainability: 4,
    energy_level: 2,
    shedding: true,
    popularity_rank: 6,
    history: ""
  },
  {
    breed: "Poodle",
    breed_group: "Non-Sporting Group",
    breed_summary: "Intelligent and active.",
    image_file_name: "breed-poodle.jpg",
    height_min: 10,
    height_max: 15,
    weight_min: 4,
    weight_max: 50,
    dog_size: "Tiny, Small and Medium",
    life_min: 10,
    life_max: 18,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 4,
    trainability: 5,
    energy_level: 4,
    shedding: false,
    popularity_rank: 7,
    history: ""
  },
  {
    breed: "Rottweiler",
    breed_group: "Working Group",
    breed_summary: "Loyal and reserved.",
    image_file_name: "breed-rottweiler.jpg",
    height_min: 22,
    height_max: 27,
    weight_min: 77,
    weight_max: 130,
    dog_size: "Very Large",
    life_min: 8,
    life_max: 10,
    affectionate: 5,
    kid_friendly: 4,
    stranger_friendly: 4,
    trainability: 4,
    energy_level: 4,
    shedding: true,
    popularity_rank: 8,
    history: ""
  },
  {
    breed: "Yorkshire Terrier",
    breed_group: "Toy Group",
    breed_summary: "Feisty and fun.",
    image_file_name: "breed-yorkshire-terrier.jpg",
    height_min: 7,
    height_max: 8,
    weight_min: 7,
    weight_max: 7,
    life_min: 11,
    life_max: 15,
    dog_size: "Tiny",
    affectionate: 4,
    kid_friendly: 2,
    stranger_friendly: 2,
    trainability: 3,
    energy_level: 5,
    shedding: false,
    popularity_rank: 9,
    history: ""
  },
  {
    breed: "Boxer",
    breed_group: "Working Group",
    breed_summary: "Active, fun, and loyal.",
    image_file_name: "breed-boxer.jpg",
    height_min: 21.5,
    height_max: 25,
    weight_min: 50,
    weight_max: 80,
    dog_size: "Large",
    life_min: 10,
    life_max: 12,
    affectionate: 5,
    kid_friendly: 4,
    stranger_friendly: 4,
    trainability: 4,
    energy_level: 5,
    shedding: true,
    popularity_rank: 10,
    history: ""
  },
 {
    breed: "German Shorthaired Pointer",
    breed_group: "Sporting Group",
    breed_summary: "Agile, fast and powerful.",
    image_file_name: "breed-german-shorthaired-pointer.jpg",
    height_min: 21,
    height_max: 25,
    weight_min: 45,
    weight_max: 70,
    dog_size: "Medium and Large",
    life_min: 10,
    life_max: 12,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 3,
    trainability: 5,
    energy_level: 5,
    shedding: true,
    popularity_rank: 11,
    history: ""
  },
 {
    breed: "Siberian Husky",
    breed_group: "Working Group",
    breed_summary: "Friendly, gentle and alert.",
    image_file_name: "breed-siberian-husky.jpg",
    height_min: 20,
    height_max: 24,
    weight_min: 35,
    weight_max: 60,
    dog_size: "Medium",
    life_min: 12,
    life_max: 15,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 3,
    trainability: 2,
    energy_level: 5,
    shedding: true,
    popularity_rank: 12,
    history: ""
  },
 {
    breed: "Shih Tzu",
    breed_group: "Toy Group",
    breed_summary: "Small, sturdy and devoted.",
    image_file_name: "breed-shih-tzu.jpg",
    height_min: 8,
    height_max: 11,
    weight_min: 9,
    weight_max: 16,
    dog_size: "Tiny",
    life_min: 10,
    life_max: 16,
    affectionate: 5,
    kid_friendly: 4,
    stranger_friendly: 3,
    trainability: 3,
    energy_level: 2,
    shedding: true,
    popularity_rank: 20,
    history: ""
  },
  {
    breed: "Basset Hound",
    breed_group: "Hound Group",
    breed_summary: "Patient, calm, and stubborn.",
    image_file_name: "breed-basset-hound.jpg",
    height_min: 12,
    height_max: 15,
    weight_min: 40,
    weight_max: 65,
    dog_size: "Medium",
    life_min: 12,
    life_max: 13,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 5,
    trainability: 2,
    energy_level: 1,
    shedding: true,
    popularity_rank: 39,
    history: ""
  },
  {
    breed: "Shiba Inu",
    breed_group: "Non-Sporting Group",
    breed_summary: "Bold, confident, and sturdy.",
    image_file_name: "breed-shiba-inu.jpg",
    height_min: 13,
    height_max: 17,
    weight_min: 15,
    weight_max: 24,
    dog_size: "Small",
    life_min: 12,
    life_max: 15,
    affectionate: 4,
    kid_friendly: 3,
    stranger_friendly: 3,
    trainability: 2,
    energy_level: 4,
    shedding: true,
    popularity_rank: 44,
    history: ""
  },
  {
    breed: "Border Collie",
    breed_group: "Herding Group",
    breed_summary: "Intelligent, athletic, and tireless.",
    image_file_name: "breed-border-collie.jpg",
    height_min: 18,
    height_max: 22,
    weight_min: 27,
    weight_max: 45,
    dog_size: "Medium",
    life_min: 10,
    life_max: 17,
    affectionate: 5,
    kid_friendly: 3,
    stranger_friendly: 5,
    trainability: 5,
    energy_level: 5,
    shedding: true,
    popularity_rank: 38,
    history: ""
  },
  {
    breed: "Chihuahua",
    breed_group: "Toy Group",
    breed_summary: "Intelligent, tiny, and enthusiastic.",
    image_file_name: "breed-chihuahua.jpg",
    height_min: 6,
    height_max: 9,
    weight_min: 3,
    weight_max: 6,
    dog_size: "Tiny",
    life_min: 12,
    life_max: 20,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 2,
    trainability: 4,
    energy_level: 2,
    shedding: true,
    popularity_rank: 30,
    history: ""
  },
  {
    breed: "Dachshund",
    breed_group: "Hound Group",
    breed_summary: "Friendly and spunky.",
    image_file_name: "breed-dachshund.jpg",
    height_min: 5,
    height_max: 9,
    weight_min: 11,
    weight_max: 32,
    dog_size: "Tiny and Small",
    life_min: 12,
    life_max: 16,
    affectionate: 4,
    kid_friendly: 5,
    stranger_friendly: 1,
    trainability: 2,
    energy_level: 3,
    shedding: true,
    popularity_rank: 13,
    history: ""
  },
  {
    breed: "Great Dane",
    breed_group: "Working Group",
    breed_summary: "Giant, sedate and friendly.",
    image_file_name: "breed-great-dane.jpg",
    height_min: 28,
    height_max: 34,
    weight_min: 100,
    weight_max: 200,
    dog_size: "Very Large",
    life_min: 6,
    life_max: 8,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 5,
    trainability: 5,
    energy_level: 5,
    shedding: true,
    popularity_rank: 14,
    history: ""
  },
  {
    breed: "Doberman Pinscher",
    breed_group: "Working Group",
    breed_summary: "Brave, alert and loyal.",
    image_file_name: "breed-doberman-pinscher.jpg",
    height_min: 24,
    height_max: 38,
    weight_min: 60,
    weight_max: 100,
    dog_size: "Large",
    life_min: 10,
    life_max: 12,
    affectionate: 5,
    kid_friendly: 3,
    stranger_friendly: 3,
    trainability: 5,
    energy_level: 3,
    shedding: true,
    popularity_rank: 15,
    history: ""
  },
  {
    breed: "Australian Shepherd",
    breed_group: "Herding Group",
    breed_summary: "Work-oriented, active and intelligent.",
    image_file_name: "breed-australian-shepherd.jpg",
    height_min: 18,
    height_max: 23,
    weight_min: 35,
    weight_max: 70,
    dog_size: "Medium",
    life_min: 13,
    life_max: 15,
    affectionate: 5,
    kid_friendly: 3,
    stranger_friendly: 2,
    trainability: 5,
    energy_level: 5,
    shedding: true,
    popularity_rank: 16,
    history: ""
  },
  {
    breed: "Miniature Schnauzer",
    breed_group: "Terrier Group",
    breed_summary: "Alert, fearless and robust.",
    image_file_name: "breed-miniature-schnauzer.jpg",
    height_min: 12,
    height_max: 14,
    weight_min: 11,
    weight_max: 20,
    dog_size: "Tiny and Small",
    life_min: 12,
    life_max: 15,
    affectionate: 5,
    kid_friendly: 3,
    stranger_friendly: 3,
    trainability: 5,
    energy_level: 5,
    shedding: false,
    popularity_rank: 17,
    history: ""
  },
  {
    breed: "Pembroke Welsh Corgi",
    breed_group: "Herding Group",
    breed_summary: "Agreeable, avid and smart.",
    image_file_name: "breed-pembroke-welsh-corgi.jpg",
    height_min: 10,
    height_max: 12,
    weight_min: 25,
    weight_max: 30,
    dog_size: "Small and Medium",
    life_min: 12,
    life_max: 13,
    affectionate: 5,
    kid_friendly: 4,
    stranger_friendly: 5,
    trainability: 5,
    energy_level: 4,
    shedding: true,
    popularity_rank: 18,
    history: ""
  },
  {
    breed: "Cavalier King Charles Spaniel",
    breed_group: "Toy Group",
    breed_summary: "Friendly, happy, and companionable.",
    image_file_name: "breed-cavalier-king-charles-spaniel.jpg",
    height_min: 12,
    height_max: 13,
    weight_min: 13,
    weight_max: 18,
    dog_size: "Tiny and Small",
    life_min: 12,
    life_max: 15,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 5,
    trainability: 4,
    energy_level: 3,
    shedding: true,
    popularity_rank: 19,
    history: ""
  },
  {
    breed: "Boston Terrier",
    breed_group: "Non-Sporting Group",
    breed_summary: "Entertaining and friendly.",
    image_file_name: "breed-boston-terrier.jpg",
    height_min: 15,
    height_max: 17,
    weight_min: 10,
    weight_max: 25,
    dog_size: "Tiny and Small",
    life_min: 13,
    life_max: 15,
    affectionate: 4,
    kid_friendly: 5,
    stranger_friendly: 4,
    trainability: 4,
    energy_level: 4,
    shedding: true,
    popularity_rank: 21,
    history: ""
  },
])