# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Dog.create!([
  {
    breed: "Pomeranian",
    breed_group: "Toy Group",
    breed_summary: "Animated, extroverted and alert.",
    image_file_name: "http://d45j0koqy9g2z.cloudfront.net/breed-pomeranian.jpg",
    height_min: 6,
    height_max: 7,
    weight_min: 3,
    weight_max: 7,
    dog_size: "Tiny",
    life_min: 12,
    life_max: 16,
    affectionate: 5,
    kid_friendly: 2,
    stranger_friendly: 3,
    trainability: 4,
    energy_level: 3,
    shedding: true,
    popularity_rank: 22,
    history: ""
    },
    {
    breed: "Havanese",
    breed_group: "Toy Group",
    breed_summary: "Curious, social and happy.",
    image_file_name: "http://d45j0koqy9g2z.cloudfront.net/breed-havanese.jpg",
    height_min: 8,
    height_max: 12,
    weight_min: 7,
    weight_max: 13,
    dog_size: "Tiny and Small",
    life_min: 14,
    life_max: 16,
    affectionate: 5,
    kid_friendly: 4,
    stranger_friendly: 5,
    trainability: 5,
    energy_level: 3,
    shedding: false,
    popularity_rank: 23,
    history: ""
  },
  {
    breed: "Shetland Sheepdog",
    breed_group: "Herding Group",
    breed_summary: "Intelligent, energetic and playful.",
    image_file_name: "http://d45j0koqy9g2z.cloudfront.net/breed-shetland-sheepdog.jpg",
    height_min: 13,
    height_max: 16,
    weight_min: 15,
    weight_max: 25,
    dog_size: "Small and Medium",
    life_min: 12,
    life_max: 14,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 5,
    trainability: 5,
    energy_level: 4,
    shedding: true,
    popularity_rank: 24,
    history: ""
  },
  {
    breed: "Brittany",
    breed_group: "Sporting Group",
    breed_summary: "Muscular, quick and tireleses.",
    image_file_name: "http://d45j0koqy9g2z.cloudfront.net/breed-brittany.jpg",
    height_min: 17.5,
    height_max: 50.5,
    weight_min: 30,
    weight_max: 40,
    dog_size: "Medium",
    life_min: 12,
    life_max: 14,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 4,
    trainability: 3,
    energy_level: 5,
    shedding: true,
    popularity_rank: 25,
    history: ""
  },
  {
    breed: "English Springer Spaniel",
    breed_group: "Sporting Group",
    breed_summary: "Hardworking, playful, friendly.",
    image_file_name: "http://d45j0koqy9g2z.cloudfront.net/breed-english-springer-spaniel.jpg",
    height_min: 19,
    height_max: 20,
    weight_min: 40,
    weight_max: 50,
    dog_size: "Medium",
    life_min: 12,
    life_max: 14,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 4,
    trainability: 5,
    energy_level: 5,
    shedding: true,
    popularity_rank: 26,
    history: ""
  },
  {
    breed: "Bernese Mountain Dog",
    breed_group: "Working Group",
    breed_summary: "Calm, good-natured and strong.",
    image_file_name: "http://d45j0koqy9g2z.cloudfront.net/breed-bernese-mountain-dog.jpg",
    height_min: 23,
    height_max: 28,
    weight_min: 80,
    weight_max: 110,
    dog_size: "Very Large",
    life_min: 6,
    life_max: 8,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 5,
    trainability: 4,
    energy_level: 4,
    shedding: true,
    popularity_rank: 27,
    history: ""
  },
  {
    breed: "Mastiff",
    breed_group: "Working Group",
    breed_summary: "Docile, courageous and dignified.",
    image_file_name: "http://d45j0koqy9g2z.cloudfront.net/breed-mastiff.jpg",
    height_min: 27.5,
    height_max: 32,
    weight_min: 120,
    weight_max: 230,
    dog_size: "Very Large",
    life_min: 6,
    life_max: 10,
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 2,
    trainability: 3,
    energy_level: 3,
    shedding: true,
    popularity_rank: 28,
    history: ""
  },
  {
    breed: "Cocker Spaniel",
    breed_group: "Sporting Group",
    breed_summary: "Active, energetic and playful.",
    image_file_name: "http://d45j0koqy9g2z.cloudfront.net/breed-cocker-spaniel.jpg",
    height_min: 13.5,
    height_max: 15.5,
    weight_min: 20,
    weight_max: 30,
    dog_size: "Small",
    life_min: 10,
    life_max: 14,
    affectionate: 5,
    kid_friendly: 3,
    stranger_friendly: 3,
    trainability: 5,
    energy_level: 4,
    shedding: true,
    popularity_rank: 29,
    history: ""
  },
  {
    breed: "Vizsla",
    breed_group: "Sporting Group",
    breed_summary: "Gentle, energetic, and athletic.",
    image_file_name: "http://d45j0koqy9g2z.cloudfront.net/breed-vizsla.jpg",
    height_min: 21,
    height_max: 24,
    weight_min: 44,
    weight_max: 60,
    life_min: 12,
    life_max: 14,
    dog_size: "Medium and Large",
    affectionate: 5,
    kid_friendly: 5,
    stranger_friendly: 5,
    trainability: 5,
    energy_level: 5,
    shedding: true,
    popularity_rank: 31,
    history: ""
  },
  {
    breed: "Pug",
    breed_group: "Toy Group",
    breed_summary: "Good-natured, playful, and outgoing.",
    image_file_name: "http://d45j0koqy9g2z.cloudfront.net/breed-pug.jpg",
    height_min: 10,
    height_max: 13,
    weight_min: 14,
    weight_max: 18,
    dog_size: "Tiny and Small",
    life_min: 13,
    life_max: 15,
    affectionate: 5,
    kid_friendly: 4,
    stranger_friendly: 4,
    trainability: 3,
    energy_level: 3,
    shedding: true,
    popularity_rank: 32,
    history: ""
  }
])